name: DocumentsAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build Images
    -  run: docker-compose build
    -  run: docker-compose down -v --remove-orphans
    -  run: docker-compose up -d
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker-compose exec -T bash flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        docker-compose exec -T bash pytest
